name: CI/CD

on:
  push:
    branches:
      - wp-pages

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Install Composer dependencies
        run: composer install
      - name: Set up MySQL service
        run: |
          sudo service mysql start
          sudo service mysql enable

      - name: Generate Keys
        run: |
          mkdir -p .github/keys
          openssl genrsa -out .github/keys/private.key 2048
          openssl rsa -pubout -in .github/keys/private.key -out .github/keys/public.key
          
      - name: Install wp-cli
        run: |
          sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          sudo chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Create wp-config.php
        run: |
          wp config create --dbname=wordpress --dbuser=root --dbpass=root --dbhost=127.0.0.1 --dbcharset=utf8 --dbcollate=
          
          
      - name: Install and activate WordPress
        run: wp core install --url=http://localhost --title=Test --admin_user=admin --admin_password=password --admin_email=admin@example.com


      - name: Run tests
        run: |
          # Add your test commands here
