name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - wp-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Database Migration (if required)
        run: |
          # Use WP-CLI or any other migration tool here to handle database schema changes or data import.

      - name: Restart Apache web server
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@YOUR_EC2_INSTANCE_IP_ADDRESS 'sudo systemctl restart httpd'

