name: CI/CD

on:
  push:
    branches:
      - wp-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Install Composer dependencies
        run: composer install

      - name: Generate Keys
        run: |
          mkdir -p .github/keys
          openssl genrsa -out .github/keys/private.key 2048
          openssl rsa -pubout -in .github/keys/private.key -out .github/keys/public.key

      - name: Install wp-cli
        run: |
          sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          sudo chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Set up MySQL
        run: |
          sudo apt-get -y install mysql-client

      - name: Create wp-config.php
        run: |
          wp config create --dbname=wordpress --dbuser=root --dbpass=root --dbhost=localhost --dbcharset=utf8 --dbcollate=

      - name: Install and activate WordPress
        run: wp core install --url=http://localhost --title=Test --admin_user=admin --admin_password=password --admin_email=admin@example.com

      - name: Run tests
        run: |
          # Add your test commands here
