name: WordPress CI/CD

on:
  push:
    branches:
      - wp-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
      - name: Run tests
        run: vendor/bin/phpunit
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
