name: CI/CD

on:
  push:
    branches:
      - wp-pages

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Install Composer dependencies
        run: composer install

      - name: Set up MySQL connection
        run: |
          echo "DB_NAME=wordpress" >> $GITHUB_ENV
          echo "DB_USER=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=root" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_CHARSET=utf8" >> $GITHUB_ENV
          echo "DB_COLLATE=" >> $GITHUB_ENV

      - name: Install wp-cli
        run: |
          sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          sudo chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Create wp-config.php
        run: |
          wp config create --dbname=wordpress --dbuser=root --dbpass=root --dbhost=mysql --dbcharset=utf8 --dbcollate=

      - name: Create WordPress directory
        run: |
          mkdir -p wordpress

      - name: Copy wp-config.php
        run: |
          cp wp-config.php wordpress/wp-config.php

      - name: Install and activate WordPress
        run: |
          wp core install --url=http://localhost --title=Test --admin_user=admin --admin_password=password --admin_email=admin@example.com

      - name: Run tests
        run: |
          # Add your test commands here
