name: Deploy to EC2

on:
  push:
    branches:
      - wp-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          whoami
          echo "${{ secrets.EC2_MANUAL }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa    
          ssh-keyscan 3.84.24.19 >> /home/runner/.ssh/known_hosts
          cat '/home/runner/.ssh/known_hosts'
          echo "end of ssh key setup"

      - name: Connect to EC2 and Run Commands
        run: |
          ssh -vvv -o StrictHostKeyChecking=no root@3.84.24.19
             echo "connection made"
             pwd
             cd
             cd /var/www/html/wordpress
             ls
