name: Deployment
on:
  push:
    branches: wp-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Build
      run: npm run build
    
