name: Deploy to EC2

on:
  push:
    branches:
      - wp-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 740 ~/.ssh/id_rsa
          ssh-keyscan 3.84.24.19 >> ~/.ssh/known_hosts
          echo "end of ssh key setup"

      - name: Connect to EC2 and Run Commands
        run: |
          ssh ubuntu@ec2-3-84-24-19 
          #ssh ubuntu@54.175.203.8 "cd /path/to/your/app && git pull origin main && npm install && npm run build"
