name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 php mysql-client

      - name: Deploy to EC2
        run: |
          # Replace the EC2_IP_ADDRESS with the public IP or DNS of your EC2 instance
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@EC2_IP_ADDRESS 'cd /var/www/html && git pull origin main'


      - name: Restart Apache Server
        run: sudo service apache2 restart
