name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - wp-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 php mysql-client

      - name: Deploy to EC2
        run: |
          # Replace the EC2_IP_ADDRESS with the public IP or DNS of your EC2 instance
          ssh -i ${{ ssh -i "wordpress-key.pem" ubuntu@ec2-52-207-106-140.compute-1.amazonaws.com }} ubuntu@52.207.106.140 'cd /var/www/html/wordpress && git pull origin wp-pages'


      - name: Restart Apache Server
        run: sudo service apache2 restart
