name: CI/CD Pipeline

on:
  push:
    branches:
      - wp-pages

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Install dependencies
        run: |
          cd wordpress
          composer install
          
      - name: Build assets
        run: |
          cd wordpress
          npm install && npm run build
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /path/to/wordpress
            git pull origin main
            # Additional deployment steps, such as copying files, running database migrations, etc.
